name: CI

on:
  push:
    branches:
      - master  # Executa o workflow quando houver push na branch 'main'
  pull_request:
    branches:
      - master  # Executa o workflow em pull requests na branch 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Define o ambiente como Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Faz o checkout do repositório

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Define a versão do Node.js

      - name: Install dependencies
        run: npm install  # Instala as dependências do projeto

      - name: Run tests
        run: npm run test:unit  # Roda os testes (altere o comando se necessário)
