name: CI Cucumber

on:
  push:
    branches:
      - main  # Executa o workflow em pushes na branch 'main'
  pull_request:
    branches:
      - main  # Executa o workflow em pull requests na branch 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Substitua pela versão desejada do Ruby

      - name: Install dependencies
        run: bundle install  # Instala as gems do Gemfile

      - name: Run Cucumber tests
        run: bundle exec cucumber  # Roda os testes com Cucumber
